### PR TITLE
Fix getSize() of a table

### PR DESCRIPTION
**Pull request by polskikh**
Sorry for the last PR.

Now I fix only `getSize()` function.

All tests passed:
```
$ make test
tests/run_tests
running test suite at: /go/src/github.com/reconquest/shadowd/tests/testcases

  .................

---
17 tests (168 assertions) done successfully!
```

### CODE REVIEW

**Comment by seletskiy** [comment]
Nice, thanks. Can you please also add testcase which fails on commit before
fix and passes with fix?

**Comment by seletskiy** [comment]
@polskikh: ping?

**Comment by polskikh** [comment]
@seletskiy sry, but I have a trouble with my free time. I can add a testcase within 3 weeks, maybe earlier. Is it ok?

**Comment by seletskiy** [comment]
@polskikh: Hey Vladislav, no problems at all, take your time!

**Pull request closed without merging**
